server:
  port: 2003
spring:
  application:
    name: eureka-client-ribbon
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:123456@localhost:2001/eureka

# 自定义属性，用于连接的url
service-url:
  user-producter: http://eureka-client-producter