server:
  port: 2005
spring:
  application:
    name: eureka-client-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:2001/eureka/

# 自定义属性，用于restTemplate连接的url
service-url:
  user-producter: http://eureka-client-producter
