server:
  port: 2008
spring:
  application:
    name: eureka-client-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/BigWhiteOne/springcloud-config
          username: bigwhiteone
          password: dw7854as123
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:2001/eureka/