server:
  port: 2010
spring:
  application:
    name: eureka-client-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: lb://eureka-client-producter
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:2001/eureka/
